MaxHistoryInMemory: 1
HTTPPort: 3000
HTTPHost: "0.0.0.0"
WorkspaceDirectory: /tmp/go-buildserver
Repos:
- URL: git@github.com:pjotrscholtze/go-buildserver.git
  Name: Go-Buildserver
  BuildScript: ./build.sh
  SSHKeyLocation: /data/.ssh/github.com
  ForceCleanBuild: True
  Triggers:
  - Kind: Cron
    Schedule: "*/15 * * * * *"
  - Kind: WebHook