openapi: 3.0.3
info:
  title: Go Buildserver
  version: 1.0.0
paths:
  /jobs:
    get:
      summary: Get jobs
      operationId: listJobs
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                type: array
                xml:
                  name: jobs
                  wrapped: true
                items:  
                  $ref: '#/components/schemas/Job'
  /pipelines:
    get:
      summary: Get pipelines
      operationId: listPipelines
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                type: array
                xml:
                  name: pipelines
                  wrapped: true
                items:  
                  $ref: '#/components/schemas/Pipeline'
  /pipeline/{name}:
    post:
      summary: Start pipeline
      description: ''
      operationId: startPipeline
      parameters:
        - name: name
          in: path
          required: true
          schema:
            type: string
      requestBody:
        content:
          application/json:
            schema:
              type: object
              additionalProperties: true
          application/xml:
            schema:
              type: object
              additionalProperties: true
          application/x-www-form-urlencoded:
            schema:
              type: object
              additionalProperties: true
        required: true
      responses:
        '200':
          description: Started pipeline
components:
  schemas:
    BuildResultLine:
      type: object
      properties:
        Line:
          type: string
        Time:
          type: string
          format: date-time
        Pipe:
          type: string
    BuildResult:
      type: object
      properties:
        StartTime:
          type: string
          format: date-time
        Status:
          type: string
        Reason:
          type: string
        Lines:
          type: array
          xml:
            wrapped: true
          items:
            $ref: '#/components/schemas/BuildResultLine'
    Trigger:
      type: object
      properties:
        Kind:
          type: string
        Schedule:
          type: string
    Job:
      type: object
      properties:
        PipelineName:
          type: string
        BuildReason:
          type: string
        Origin:
          type: string
        QueueTime:
          type: string
          format: date-time
    Pipeline:
      type: object
      properties:
        LastBuildResult:
          type: array
          xml:
            wrapped: true
          items:
            $ref: '#/components/schemas/BuildResult'
        URL:
          type: string
        Path:
          type: string
        Name:
          type: string
        BuildScript:
          type: string
        ForceCleanBuild:
          type: boolean
        Triggers:
          type: array
          xml:
            wrapped: true
          items:
            $ref: '#/components/schemas/Trigger'
