// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// ListJobsHandlerFunc turns a function with the right signature into a list jobs handler
type ListJobsHandlerFunc func(ListJobsParams) middleware.Responder

// Handle executing the request and returning a response
func (fn ListJobsHandlerFunc) Handle(params ListJobsParams) middleware.Responder {
	return fn(params)
}

// ListJobsHandler interface for that can handle valid list jobs params
type ListJobsHandler interface {
	Handle(ListJobsParams) middleware.Responder
}

// NewListJobs creates a new http.Handler for the list jobs operation
func NewListJobs(ctx *middleware.Context, handler ListJobsHandler) *ListJobs {
	return &ListJobs{Context: ctx, Handler: handler}
}

/* ListJobs swagger:route GET /jobs listJobs

Get jobs

*/
type ListJobs struct {
	Context *middleware.Context
	Handler ListJobsHandler
}

func (o *ListJobs) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewListJobsParams()
	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
