// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/pjotrscholtze/go-buildserver/models"
)

// ListReposOKCode is the HTTP code returned for type ListReposOK
const ListReposOKCode int = 200

/*ListReposOK Successful operation

swagger:response listReposOK
*/
type ListReposOK struct {

	/*
	  In: Body
	*/
	Payload []*models.Repo `json:"body,omitempty"`
}

// NewListReposOK creates ListReposOK with default headers values
func NewListReposOK() *ListReposOK {

	return &ListReposOK{}
}

// WithPayload adds the payload to the list repos o k response
func (o *ListReposOK) WithPayload(payload []*models.Repo) *ListReposOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the list repos o k response
func (o *ListReposOK) SetPayload(payload []*models.Repo) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *ListReposOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	payload := o.Payload
	if payload == nil {
		// return empty array
		payload = make([]*models.Repo, 0, 50)
	}

	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}
}
