// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// ListReposHandlerFunc turns a function with the right signature into a list repos handler
type ListReposHandlerFunc func(ListReposParams) middleware.Responder

// Handle executing the request and returning a response
func (fn ListReposHandlerFunc) Handle(params ListReposParams) middleware.Responder {
	return fn(params)
}

// ListReposHandler interface for that can handle valid list repos params
type ListReposHandler interface {
	Handle(ListReposParams) middleware.Responder
}

// NewListRepos creates a new http.Handler for the list repos operation
func NewListRepos(ctx *middleware.Context, handler ListReposHandler) *ListRepos {
	return &ListRepos{Context: ctx, Handler: handler}
}

/* ListRepos swagger:route GET /repos listRepos

Get repos

*/
type ListRepos struct {
	Context *middleware.Context
	Handler ListReposHandler
}

func (o *ListRepos) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewListReposParams()
	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
