// Code generated by go-swagger; DO NOT EDIT.

// Package restapi Go Buildserver
//
//  Schemes:
//    http
//  Host: localhost
//  BasePath: /api
//  Version: 1.0.0
//
//  Consumes:
//    - application/json
//    - application/x-www-form-urlencoded
//    - application/xml
//
//  Produces:
//    - application/json
//    - application/xml
//
// swagger:meta
package restapi
